### ISSUE TITLE
build_transformer_model 中断

### ISSUE THREAD

**Issue by MrSworder** [CLUEbenchmark/KgCLUE#4]
在尝试运行sim/train.py时，程序常常在不报错的情况下中断，在jupyter中尝试运行，发现在运行如下代码时，提示：内核似乎挂掉了，它很快将自动重启。
# 加载预训练模型
bert = build_transformer_model(
    config_path=config_path,
    checkpoint_path=checkpoint_path,
    with_pool=True,
    return_keras_model=False,
)

请问这是什么原因？是cpu或GPU不支持运行这一程序吗

**Comment by MrSworder** [comment]
问题解决了...
初始化模型文件缺失导致的

**Comment by brightmart** [comment]
好
